<a href="https://colab.research.google.com/github/saja13-zh/ANN/blob/main/lab3_ANN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#the pureline function
def purelin(a):
  return a

#feedforward function calculate the a and pass it into pureline function
def feedforward(p,w,b):
  a=np.dot(w,p.T)+b
  a1=purelin(a)
  return a1

pt1=np.array([[1,-1,-1]])
pt2=np.array([[1,1,-1]])
w=np.concatenate((pt1,pt2))
b=np.array([[3,3]]).T

print(w)
print(b)

p1=np.array([[1,-1,-1]])
a1=feedforward(p1,w,b)
print(f"p=[1,-1,-1] a1={a1}\n")

p2=np.array([[1,1,-1]])
a2=feedforward(p2,w,b)
print(f"p=[1,-1,-1] a1={a2}\n")

p3=np.array([[-1,-1,-1]])
a3=feedforward(p3,w,b)
print(f"p=[1,-1,-1] a1={a3}\n")

p4=np.array([[-1,1,-1]])
a4=feedforward(p4,w,b)
print(f"p=[1,-1,-1] a1={a4}\n")

[[ 1 -1 -1]
 [ 1  1 -1]]
[[3]
 [3]]
p=[1,-1,-1] a1=[[6]
 [4]]

p=[1,-1,-1] a1=[[4]
 [6]]

p=[1,-1,-1] a1=[[4]
 [2]]

p=[1,-1,-1] a1=[[2]
 [4]]



In [ ]:
#function for positive linear
def positive(n):
  if n<0:
    return 0
  else:
    return n

def recurrentlayer(a1,w,t):
  if(t==0):
    return a1
  else:
    a2=a1
    for i in range(1,t+1):
      n=np.dot(w,a2)
      a=[]
      for item in n:
        a.append(positive(item))
      a2=a

  return a2

a1=np.array([[4,2]]).T
w=np.array([[1,-0.5],[-0.5,1]])
print(recurrentlayer(a1,w,0))
print(recurrentlayer(a1,w,1))
print(recurrentlayer(a1,w,2))

[[4]
 [2]]
[array([3.]), array([0.])]
[array([3.]), 0]


In [ ]:
#the pureline function
def purelin(a):
  return a

#feedforward function calculate the a and pass it into pureline function
def feedforward(p,w,b):
  a=np.dot(w,p.T)+b
  a1=purelin(a)
  return a1

#function for positive linear
def positive(n):
  if n<0:
    return 0
  else:
    return n

def recurrentlayer(a1,w,t):
  if(t==0):
    return a1
  else:
    a2=a1
    for i in range(1,t+1):
      n=np.dot(w,a2)
      a=[]
      for item in n:
        a.append(positive(item))
      a2=a

  return a2


pt1=np.array([[1,-1,-1]])
pt2=np.array([[1,1,-1]])
w1=np.concatenate((pt1,pt2))
b=np.array([[3,3]]).T
P1=np.array([[1,1,1]])
w2=np.array([[1,-0.5],[-0.5,1]])
a1=np.array([[4,2]]).T
a1=feedforward(P1,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}\n")

P2=np.array([[1,1,-1]])
a1=feedforward(P2,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}\n")

P3=np.array([[1,-1,1]])
a1=feedforward(P3,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}\n")

P4=np.array([[1,-1,-1]])
a1=feedforward(P4,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}\n")

P5=np.array([[-1,1,1]])
a1=feedforward(P5,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}\n")

P6=np.array([[-1,1,-1]])
a1=feedforward(P6,w1,b)
print(f"a2(1)= {recurrentlayer(a1,w2,1)}")
print(f"a2(2)= {recurrentlayer(a1,w2,2)}")

a2(1)= [array([0.]), array([3.])]
a2(2)= [0, array([3.])]

a2(1)= [array([1.]), array([4.])]
a2(2)= [0, array([3.5])]

a2(1)= [array([3.]), array([0.])]
a2(2)= [array([3.]), 0]

a2(1)= [array([4.]), array([1.])]
a2(2)= [array([3.5]), 0]

a2(1)= [0, array([2.])]
a2(2)= [0, array([2.])]

a2(1)= [array([0.]), array([3.])]
a2(2)= [0, array([3.])]
